### ISSUE TITLE
SigmaStar SSC335: Majestic - Image - Flip horizontally or vertically does not work

### ISSUE THREAD

**Issue by n0rthernstar** [OpenIPC/majestic#145]
# Required information

chip:
  vendor: SigmaStar
  model: SSC33X
  family: infinity6b0
  id: 15839036010E
  tag: MVX1##I6gf74c9b5CMN_ROM######XVM
board:
  vendor: OpenIPC
  version: 2.3.12.12
ethernet:
  mac: "da:9f:28:95:c4:30"
rom:
- type: nor
  block: 64K
  partitions:
    - name: boot
      size: 0x40000
      sha1: 75e88cad
    - name: env
      size: 0x10000
      sha1: d83f8652
      contains:
        - name: uboot-env
          offset: 0x0
    - name: kernel
      size: 0x200000
      sha1: 42b82828
    - name: rootfs
      size: 0x800000
      sha1: 5fc5c185
    - name: rootfs_data
      size: 0x5b0000
      path: /overlay,jffs2,rw
  size: 16M
ram:
  total: 64M
  media: 32M
firmware:
  u-boot: "2015.01 (Nov 01 2023 - 01:33:17)"
  kernel: "4.9.84 (PREEMPT Tue Dec 12 07:51:59 UTC 2023)"
  toolchain: buildroot-gcc-12.3.0
  main-app: /usr/bin/majestic
sensors:
- vendor: GalaxyCore
  model: GC2053
  control:
    bus: 0
    type: i2c
    addr: 0x6e

# Issue description

After writing image of openipc on  the camera (vstarcam c8838wp; processor - SigmaStar SSC335) image is upside down. Going to Majestic - Image and setting 
Flip image horizontally 
Flip image vertically
has no effect on the image - both on previer or /video.mp4 endpoint

# Expectations

Image would flip horiz and vertically

# Steps to reproduce

Majestic -> Image
SET
Flip image horizontally - on
Flip image vertically - on
Reboot

# Information to attach

 - [ ] Any relevant log output (`logread -f`)
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: ===== MhalCameraClose begin, ch = 0, VifMask: 0x3 =====
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: ===== MhalCameraClose, 11058 end. =====
Dec 12 12:35:59 openipc-ssc335 user.info majestic[857]: Using /etc/majestic.yaml as main configuration
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: i2c-1 timeout
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: i2c-1 timeout
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: CamOsMutexInit already inited, LR:0xBF84210B
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: CameraIsp_EnableChannel3A, ch:0 data:  (null)
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: CameraIsp_EnableCus3A AE=1, AWB=0, AF=0
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: CameraIsp_EnableChannel3A, ch:0 data:  (null)
Dec 12 12:35:59 openipc-ssc335 kern.err kernel: CameraIsp_EnableCus3A AE=1, AWB=1, AF=0
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: ===== [MhalCameraOpen] begin ===== VifMask : 3
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: Ch= 0, SNR ID: 0x0, VifCh = 0x0, PreOpen = 0
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: 3DNR = 2, Rotation = 0, AckTie : 0
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: (W, H): (1920, 1080)
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: PixelFmt: 1, BayerID: 0, YuvOrder: 0
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: Mode: 0, HdrType: 0
Dec 12 12:36:00 openipc-ssc335 kern.err kernel: [CameraReadIqData] isp root is /etc/firmware, nCh = 0
 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)
root@openipc-ssc335:~# cat /etc/majestic.yaml
system:
  webAdmin: enabled
  buffer: 1024
image:
  mirror: true
  flip: true
  rotate: none
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
osd:
  enabled: false
  template: "%a %e %B %Y %H:%M:%S %Z"
nightMode:
  enabled: false
  nightAPI: false
  irSensorPinInvert: false
  irCutSingleInvert: false
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F/%H.mp4
  maxUsage: 95
video0:
  enabled: true
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: false
  volume: auto
  srate: 8000
rtsp:
  enabled: true
  port: 554
hls:
  enabled: false
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: false
  debug: false
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 10

**Comment by flyrouter** [comment]
Hi
Please upgrade firmware and probe again
Thank you

**Comment by n0rthernstar** [comment]
It works! Thank you very much!

**Comment by arcidodo** [comment]
I have the same issue with the newest firmware.

```
Nov  3 17:07:10 openipc-ssc335 user.info majestic[669]: Signal HUP received, reloading config
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: [_MI_AI_IMPL_FreeTmpBuffer:3819] free tmp buffer.
Nov  3 17:07:11 openipc-ssc335 kern.warn kernel: ^[[1;31m[HALSCL]_HalSclDestoryRealTimeModeOrLastChannel Destroy process fence cd 
Nov  3 17:07:11 openipc-ssc335 kern.warn kernel: ^[[m
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: ===== MhalCameraClose begin, ch = 0, VifMask: 0x3 ===== 
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: ===== MhalCameraClose, 11058 end. ===== 
Nov  3 17:07:11 openipc-ssc335 user.info majestic[669]: Loading main configuration: /etc/majestic.yaml
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: CamOsMutexInit already inited, LR:0xBF8EB10B
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: CamOsMutexInit already inited, LR:0xBF8EB067
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: CameraIsp_EnableChannel3A, ch:0 data:  (null)
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: CameraIsp_EnableCus3A AE=1, AWB=0, AF=0
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: CameraIsp_EnableChannel3A, ch:0 data:  (null)
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: CameraIsp_EnableCus3A AE=1, AWB=1, AF=0
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: [_MI_AI_IMPL_AllocTmpBuffer:3801] tmp buffer addr[c6086000].
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: ===== [MhalCameraOpen] begin ===== VifMask : 3
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: Ch= 0, SNR ID: 0x0, VifCh = 0x0, PreOpen = 0
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: 3DNR = 2, Rotation = 0, AckTie : 0
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: (W, H): (2304, 1296)
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: PixelFmt: 1, BayerID: 2, YuvOrder: 0
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: Mode: 0, HdrType: 0
Nov  3 17:07:11 openipc-ssc335 kern.err kernel: [CameraReadIqData] isp root is /etc/firmware, nCh = 0
Nov  3 17:07:12 openipc-ssc335 user.info majestic[669]: RTSP server started on port 554
```



```
root@openipc-ssc335:/usr/bin# cat /etc/majestic.yaml 
system:
  webPort: 80
  httpsPort: 443
  logLevel: info
  buffer: 1024
  plugins: false
  unsafe: false
isp:
  antiFlicker: 50
  iqServer: false
  sensorConfig: /etc/sensors/sc401ai.bin
image:
  mirror: true
  flip: true
  rotate: 0
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 50
video0:
  enabled: true
  codec: h264
  fps: 15
  bitrate: 4096
  rcMode: vbr
  gopSize: 1
  profile: high
  size: 2304x1296
  sliceUnits: 0
video1:
  enabled: true
  codec: h264
  size: 640x360
  fps: 15
  bitrate: 1024
  profile: main
  rcMode: vbr
jpeg:
  enabled: true
  qfactor: 50
  fps: 5
osd:
  enabled: false
  font: /usr/share/fonts/truetype/UbuntuMono-Regular.ttf
  template: '%d.%m.%Y %H:%M:%S'
  posX: 16
  posY: 16
  size: 1.0
audio:
  enabled: true
  volume: 30
  srate: 8000
  codec: opus
  outputEnabled: true
  outputVolume: 30
  speakerPin: 61
  speakerPinInvert: false
rtsp:
  enabled: true
  port: 554
nightMode:
  colorToGray: true
  irCutSingleInvert: false
  lightMonitor: true
  lightSensorInvert: false
  irCutPin1: 78
  backlightPin: 14
  monitorDelay: 16
  maxThreshold: 10000
  minThreshold: 1000
motionDetect:
  enabled: false
  visualize: false
  debug: false
records:
  enabled: false
  path: /mnt/mmcblk0p1/%F
  split: 20
  maxUsage: 95
outgoing:
  enabled: false
watchdog:
  enabled: true
  timeout: 300
hls:
  enabled: false
onvif:
  enabled: true
```

```
root@openipc-ssc335:/usr/bin# ipctool
---
chip:
  vendor: SigmaStar
  model: SSC33X
  family: infinity6b0
  id: 42BEEFA88E7D
  tag: "MVX1##I6gf74c9b5CMN_ROM######XVMd?\u0002"
board:
  vendor: OpenIPC
  version: 2.5.11.03
ethernet:
  mac: "00:00:23:34:45:66"
rom:
- type: nor
  block: 64K
  partitions:
    - name: boot
      size: 0x40000
      sha1: c359b802
    - name: env
      size: 0x10000
      sha1: 2aebeb5a
      contains:
        - name: uboot-env
          offset: 0x0
    - name: kernel
      size: 0x200000
      sha1: 76ba2dc2
    - name: rootfs
      size: 0x500000
      sha1: 73f5717a
    - name: rootfs_data
      size: 0xb0000
      path: /overlay,jffs2,rw
  size: 8M
ram:
  total: 64M
  media: 32M
firmware:
  u-boot: "2015.01 (Aug 23 2025 - 18:56:24)"
  kernel: "4.9.84 (PREEMPT Mon Nov 3 04:02:25 UTC 2025)"
  toolchain: buildroot-gcc-13.3.0
  main-app: majestic
sensors:
- vendor: SmartSens
  model: SC3335
  control:
    bus: 0
    type: i2c
    addr: 0x60
```
