### ISSUE TITLE
Multiple outgoing RTMP connections: 1) How to define? 2) Invalid YAML in documentation example, but accepted by Majestic.

### ISSUE THREAD

**Issue by usa-** [OpenIPC/majestic#178]
How to define multiple outgoing RTMP connections?
E. g. 
```yaml
outgoing:
  enabled: true
  naluSize: 1200
  server:
    - rtmp://a.rtmp.youtube.com/live2/key1
    - rtmp://a.rtmp.youtube.com/live2/key2
 ```
or, even better:
```yaml
outgoing:
  - enabled: true
    naluSize: 1200
    server: rtmp://a.rtmp.youtube.com/live2/key1
  - enabled: true
    naluSize: 1200
    server: rtmp://a.rtmp.youtube.com/live2/key2
 ```
These theoretical examples do not work, video is being sent to the 1st server only.

[Documentation](https://github.com/OpenIPC/wiki/blob/master/en/majestic-streamer.md#other-outgoing-options) contains **INVALID** YAML in the corresponding section:

```yaml
outgoing:
  enabled: true
  server: udp://192.168.1.10:5600
  naluSize: 1200
  - udp://IP-1:port
  - udp://IP-2:port
  - unix:/tmp/rtpstream.sock
  - rtmps://dc4-1.rtmp.t.me/s/mykey
```
You can check it with any YAML validator.

But Majestic successfully parses it. However, video is only sent to the 1st RTMP server, again.
