### ISSUE TITLE
OSD does not work Rotate image clockwise 90 and 270 degrees

### ISSUE THREAD

**Issue by CAMOKATBETEPAHA** [OpenIPC/majestic#180]
ssc338q (infinity6e family), imx415, 16 MB nor flash, 2.4.08.26-lite, openipc-ssc338q

If you set the vertical display resolution (Rotate image clockwise 90 or 270), then the OSD is not displayed, as well as the private mask.

If you change the display to horizontal resolution (Rotate image clockwise 0), then the display of the OSD and private mask returns. Changing the flip does not affect.

```
isp:
  antiFlicker: disabled
  drc: 200
  iqServer: false
  sensorConfig: /etc/sensors/imx415.bin
  exposure: 0
image:
  mirror: false
  flip: false
  rotate: 90
  contrast: 50
  hue: 50
  saturation: 50
  luminance: 23
video0:
  enabled: true
  codec: h265
  fps: 20
  bitrate: 8000
  rcMode: avbr
  gopSize: 1.0
  profile: main
  size: 3840x2160
  sliceUnits: 0
video1:
  enabled: true
  codec: h264
  size: 960x540
  fps: 15
  bitrate: 1000
  profile: main
  rcMode: avbr
osd:
  enabled: true
  font: "/usr/share/fonts/truetype/UbuntuMono-Regular.ttf"
  template: "%d.%m.%Y %H:%M:%S"
  posX: -1
  posY: -2
  privacyMasks: 2000x1000x100x100
```
The "trial and error" method of changing coordinates does not help.
