### ISSUE TITLE
Multiple outgoing RTMP connections: 1) How to define? 2) Invalid YAML in documentation example, but accepted by Majestic.

### ISSUE THREAD

**Issue by iGraveD** [OpenIPC/majestic#209]
How to define multiple outgoing RTMP connections?
E. g. 
```yaml
outgoing:
  enabled: true
  naluSize: 1200
  server:
    - rtmp://a.rtmp.youtube.com/live2/key1
    - rtmp://a.rtmp.youtube.com/live2/key2
 ```
or, even better:
```yaml
outgoing:
  - enabled: true
    naluSize: 1200
    server: rtmp://a.rtmp.youtube.com/live2/key1
  - enabled: true
    naluSize: 1200
    server: rtmp://a.rtmp.youtube.com/live2/key2
 ```
These theoretical examples do not work, video is being sent to the 1st server only.

[Documentation](https://github.com/OpenIPC/wiki/blob/master/en/majestic-streamer.md#other-outgoing-options) contains **INVALID** YAML in the corresponding section:

```yaml
outgoing:
  enabled: true
  server: udp://192.168.1.10:5600
  naluSize: 1200
  - udp://IP-1:port
  - udp://IP-2:port
  - unix:/tmp/rtpstream.sock
  - rtmps://dc4-1.rtmp.t.me/s/mykey
```
You can check it with any YAML validator.

But Majestic successfully parses it. However, video is only sent to the 1st RTMP server, again.

**Comment by widgetii** [comment]
Multiple outgoing RTMP destinations work in current releases. The key is `servers` (plural), a list — each entry is started as its own connection:

```yaml
outgoing:
  enabled: true
  naluSize: 1200
  servers:
    - rtmp://a.rtmp.youtube.com/live2/key1
    - rtmp://a.rtmp.youtube.com/live2/key2
```

Why your two attempts did not work:

* The first used `server` (singular) as a list. `server` is a single string kept for backward compatibility; the list goes under `servers`. If you already have a single `server:` line it still works and is simply added alongside anything in `servers`.
* The second nested a list of full `outgoing` blocks. `outgoing` is one section, not a list of sections — per-destination settings like `naluSize` are shared across all of them; only the URLs vary.

On the documentation: you are right, that YAML is malformed (a mapping cannot have loose `- item` entries under it). It needs correcting in the wiki, which is a separate repository — I will get it fixed there. Separately, the configuration parser has since been replaced and is stricter about malformed input, so that example would no longer be quietly accepted the way it was when you filed this.

The behaviour you actually hit — video going to the first server only — is resolved: with the `servers` list above, every RTMP/RTMPS destination is connected. Closing as done; please reopen if it does not behave that way for you on a current build.
