### ISSUE TITLE
How can I configure video filenames to be saved in ascending numerical order?

### ISSUE THREAD

**Issue by lida2003** [OpenIPC/majestic#226]
Currently, majestic is configured as follows by default, which end in kind of `2025-01-17/02-46.mp4`.

But I want to set video file name `0001.mp4` `0002.mp4` ....

```
records:
  enabled: true
  path: /mnt/mmcblk0p1/%F
  split: 20
  maxUsage: 95
```
