### ISSUE TITLE
Request to add GPIO for sound speaker control

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic#32]
When conducting experiments with video cameras that have sound speaker, it turned out that you need to be able to control an additional GPIO (activates the low frequency amplifier).
Please add this to the functionality of the next release.

```
audio:           
  enabled: true                
  volume: auto                                              
  srate: 8000     
  SpeakerPin: 8                       <= Add this
  SpeakerPinInvert: false             <= and this, please
```

**Comment by widgetii** [comment]
Implemented in the latest release:

```yaml
audio:
  enabled: true
  outputEnabled: true
  speakerPin: 32
  speakerPinInvert: false
```
