### ISSUE TITLE
Request to add GPIO for SD/MMC card control

### ISSUE THREAD

**Issue by ZigFisher** [OpenIPC/majestic#33]
When conducting experiments with video cameras that have SD/MMC card, it turned out that you need to be able to control an additional GPIO (activates the power for card).
Please add this to the functionality of the next release.

```
records:
  enabled: false
  path: /mnt/mmc/%Y/%m/%d/%H.mp4
  maxUsage: 95
  CardPin: 8                       <= Add this
  CardPinInvert: false             <= and this, please
```
