### ISSUE TITLE
[BUG] Hi3518EV300 frequent reboots caused by OOM

### ISSUE THREAD

**Issue by Droid-MAX** [OpenIPC/majestic#87]
# Required information

 * Camera board id: 02203a86de0038f98869090a5308df1424a48110615439e3
 * OpenIPC version: ultimate
 * Commit: 91df33f194552b8e11efc695a242abbc589b1a2d
 * Branch: master
 * Tag: latest
 * installation method: manual, flash openipc bootloader via programmer first, then flash kernel and rootfs via uboot command
 * modified majestic.yaml: yes, it was a problem from the beginning
 * killall majestic
   ulimit -c unlimited
   echo /tmp/%e.%p.%s.%t.core > /proc/sys/kernel/core_pattern
   majestic
   Core dump file from /tmp/ , e.g. /tmp/majestic.806.11.1619707881.core

# Issue description

A brief description of the problem. Should include what you were
attempting to do, what you did, what happened and what you expected to
see happen.

# Expectations

# Steps to reproduce

 1. the board boot up
 2. interactive by uart or wifi network normally and access service etc.
 3. reboot randomly

# Information to attach

 - [ ] Caminfo dumped by ipctool:

```
---
board:
  vendor: OpenIPC
  version: 2.2.11.26
chip:
  vendor: HiSilicon
  model: 3518EV300
  id: 02203a86de0038f98869090a5308df1424a48110615439e3
ethernet:
  mac: "8c:be:be:11:37:11"
  u-mdio-phyaddr: 1
  phy-id: 0x00000000
  d-mdio-phyaddr: 0
rom:
  - type: nor
    block: 64K
    partitions:
      - name: boot
        size: 0x40000
        sha1: 6b4a1da6
      - name: env
        size: 0x10000
        sha1: 56049650
        contains:
          - name: uboot-env
            offset: 0x0
      - name: kernel
        size: 0x300000
        sha1: 04ebb450
      - name: rootfs
        size: 0xa00000
        sha1: c26ce8ec
      - name: rootfs_data
        size: 0x2b0000
        path: /overlay,jffs2,rw
    size: 16M
    addr-mode: 3-byte
ram:
  total: 64M
  media: 32M
firmware:
  kernel: "4.9.37 (Sat Nov 26 11:34:29 UTC 2022)"
  toolchain: gcc version 8.4.0 (Buildroot -gff5aa3b6-dirty)
  sdk: "Hi3516EV200_MPP_V1.0.1.2 B030 Release (Oct 18 2019, 18:21:00)"
  main-app: /usr/bin/majestic
sensors:
- vendor: GalaxyCore
  model: GC2053
  control:
    bus: 0
    type: i2c
    addr: 0x6e
  data:
    type: MIPI
    input-data-type: DATA_TYPE_RAW_10BIT
    lane-id:
    - 0
    - 1
    image: 1920x1080
  clock: 27MHz
```

 - [ ] Any relevant log output (`dmesg`)

![image_2022-11-29_16-41-25](https://user-images.githubusercontent.com/12762435/204533303-d2f35495-14ec-4c16-897e-4ef0ed78d5ed.png)

![image_2022-11-29_16-43-09](https://user-images.githubusercontent.com/12762435/204533352-1fe9e4b4-c2ce-4a15-8f00-bee8463ec7b0.png)

 - [ ] majestic.yaml configuration (`cat /etc/majestic.yaml`)

```
 system:
  webAdmin: enabled
  buffer: 1024
image:
  mirror: false
  flip: false
  rotate: none
  contrast: auto
  hue: 50
  saturation: 50
  luminance: auto
osd:
  enabled: false
  template: "%a %e %B %Y %H:%M:%S %Z"
nightMode:
  enabled: false
records:
  enabled: false
  path: /mnt/mmcblk0p1/%Y/%m/%d/%H.mp4
  maxUsage: 95
video0:
  enabled: true
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: true
  volume: auto
  srate: 8000
  speakerPinInvert: false
  device: /dev/ai
  outputEnabled: false
rtsp:
  enabled: true
  port: 554
hls:
  enabled: true
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: true
  debug: true
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 15
```
