### ISSUE TITLE
HI3518EV200 handle_rtp

### ISSUE THREAD

**Issue by TalusL** [OpenIPC/majestic#99]
HI3518EV200 use example handle_rtp.c to handle rtp got error:```connect: No such file or directory```

how can i get sock ```/tmp/rtpstream.sock``` enable

**Comment by widgetii** [comment]
Please attach a copy of your `/etc/majestic.yaml`

**Comment by TalusL** [comment]
> Please attach a copy of your `/etc/majestic.yaml`
@widgetii thanks for your help,it`s below
```yaml
system:
  webAdmin: enabled
  buffer: 1024
image:
  mirror: false
  flip: false
  rotate: none
  contrast: auto
  hue: 50
  saturation: 50
  luminance: auto
osd:
  enabled: true
  template: "%a %e %B %Y %H:%M:%S %Z"
  posX: 16
  posY: 16
nightMode:
  enabled: true
  nightAPI: false
  irSensorPin: 62
  irSensorPinInvert: false
  irCutPin1: 1
  irCutPin2: 1
  backlightPin: 63
records:
  enabled: false
  path: /mnt/mmc/%Y/%m/%d/%H.mp4
  maxUsage: 95
video0:
  enabled: true
  fps: 15
  bitrate: 1024
  size: 1280x720
video1:
  enabled: false
jpeg:
  enabled: true
mjpeg:
  size: 640x360
  fps: 5
  bitrate: 1024
audio:
  enabled: true
  volume: auto
  srate: 44100
  speakerPinInvert: false
  codec: aac
  outputEnabled: false
rtsp:
  enabled: true
  port: 554
hls:
  enabled: true
youtube:
  enabled: false
motionDetect:
  enabled: false
  visualize: true
  debug: true
ipeye:
  enabled: false
watchdog:
  enabled: true
  timeout: 10
isp:
  lowDelay: true
cloud:
  enabled: false
```
